production:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD"] %>
  api_key: <%= ENV["CLOUDINARY_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>

development:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD"] %>
  api_key: <%= ENV["CLOUDINARY_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>

test:
  cloud_name: name
  api_key: key
  api_secret: secret
