default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: beerhunt_development

test:
  <<: *default
  database: beerhunt_test

production:
  <<: *default
  database: beerhunt_production
  password: <%= ENV['BEERHUNT_DATABASE_PASSWORD'] %>
